[params]
    brand = "Krähenbeißer"
    #brand_logo = "images/kraehenbeisser.svg"
    description = "Historische Abbildungen von Krähenbeißern"
    errorimg = "/images/kraehenbeisser.svg"
    rssinmenu = true
    keywords = "Krähenbeißer, Krajebieter, Kurische Nehrung, Kurisches Haff, Curonian Lagoon, Curonian Spit"
    stylesheets = []
    copyrightYears = "MMXXI - MMXXIII"
    cc = false
    disableScale = true
    debug = false

    [params.preview]
        outputPrefix = "ogPreview-overlay"
        outputSuffix = ".png"
        format =  "svg"
        image = "front.png"
        source = "overlay"
        [params.preview.size]
            height = 630
            width = 1200
        [params.preview.svg]
            template = "./Source Files/Other/preview-template.svg"
            scale = "width"
            removeMissing = true

    [params.footer]
        privacy = true

[params.author]
  email = 'mail@christianmahnke.de'
  name = 'Christian Mahnke'
  uri = 'http://www.wikidata.org/entity/Q137668638'
